version: '3.5'

services:
    nginx-students:
        container_name: nginx-students
        image: nginx:1.24.0
        restart: "no"
        ports:
            - "8095:80"
        volumes:
            - .:/var/www/
            # конфигурация nginx
            - ./.docker/config/nginx/:/etc/nginx/conf.d/
            # логи
            - ./.docker/logs/nginx:/var/log/nginx/
        networks:
            - web-network-students

    php-students:
        build:
            context: ./.docker/
        container_name: php-students
        restart: "no"
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www/
        networks:
            - web-network-students

    mysql-students:
        container_name: mysql-students
        image: mariadb:11.1.2
        restart: "no"
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./logs/mysql/:/var/logs/mysql
            - db-mysql:/var/lib/mysql
        security_opt:
            - seccomp:unconfined
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - web-network-students

volumes:
    db-mysql:

networks:
    web-network-students:
        name: web-network-students
